### ISSUE TITLE
Do poprawy

### ISSUE THREAD

**Issue by kacgrzes** [patmaz/js-bootcamp-node02#1]
- [x] brakuje obsługi błędów przy próbie odczytu plików (funkcja `readFile`) dodaj chociaż jakiś jeden if, który albo będzie rzucał błędem jeśli wystąpi jakikolwiek błąd, albo wywoła metodę `console.error`. Przy próbie wyrzucenia błędu należy opakować kod w dodatkową strukturę
``` js
try {
    // kod mogący potencjalnie wyrzucić błąd
} catch(err) {
    // wyłapanie i obsługa błędu
}
```

**Comment by patmaz** [comment]
checked :)
thx

**Comment by patmaz** [comment]
poprawki: https://github.com/patmaz/js-bootcamp-node02/commit/b07b2004b3623ea7b5985f3e8b144eb1203d62fd
czy ten komentarz nie sugeruje, aby ładować funkcje asynchroniczne w `try catch` ? ;)

**Comment by kacgrzes** [comment]
tę kwestię już zdążyliśmy już omówić na rozmowie :)
